apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-ml-app
  template:
    metadata:
      labels:
        app: insurance-ml-app
    spec:
      containers:
      - name: insurance-ml-app
        image: gcr.io/$GCP_PROJECT_ID/insurance-ml-app:$GITHUB_SHA
        ports:
        - containerPort: 8080
